#!/bin/sh
set -e

ssl_dir="/opt/ssl"

if [ ! "$SERVER_HOSTNAME" ]; then export SERVER_HOSTNAME=example.com; fi


#If LDAP_TLS_CACERT is set then write it out as a file
#and set up the LDAP client conf to use it.

if [ "$LDAP_TLS_CACERT" ]; then
  echo "$LDAP_TLS_CACERT" >/opt/ca.crt
  sed -i "s/TLS_CACERT.*/TLS_CACERT \/opt\/ca.crt/" /etc/ldap/ldap.conf
fi

########################
#Create Apache config


if [ -f "/opt/tls/chain.pem" ]; then $ssl_chain="SSLCertificateChainFile /opt/tls/chain.pem"; fi

cat <<EoC >/etc/apache2/sites-enabled/lum.conf

Listen 80

<VirtualHost *:80>

 ServerName $SERVER_HOSTNAME
 DocumentRoot /opt/ldap_user_manager

 DirectoryIndex index.php index.html

 <Directory /opt/ldap_user_manager>
   Require all granted
 </Directory>

 php_value include_path "/opt/ldap_user_manager/includes"

</VirtualHost>
EoC


########################
#Run Apache

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
